// <auto-generated />
using System;
using Bookshelf.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookshelf.DAL.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20181023102209_AdditionalBook")]
    partial class AdditionalBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookshelf.BL.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("ISBN");

                    b.Property<int?>("LoanedTo");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, Author = "Aleksandar", ISBN = "ISBN", Title = "Mojata borba" },
                        new { Id = 2, Author = "Petar", ISBN = "ISBN2", Title = "Borbata na Petar" },
                        new { Id = 3, Author = "Marija", ISBN = "ISBN3", Title = "Prolet" },
                        new { Id = 4, Author = "Petranka", ISBN = "ISBN4", Title = "Esen" },
                        new { Id = 5, Author = "Marija", ISBN = "ISBN5", Title = "Zimata dojde vo mojot kraj" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
