// <auto-generated />
using System;
using Bookshelf.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookshelf.DAL.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    partial class BooksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookshelf.BL.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("ISBN");

                    b.Property<int?>("LoanedTo");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.HasIndex("LoanedTo");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, Author = "Steve Kinney", ISBN = "9781617294143", Title = "Electron in Action" },
                        new { Id = 2, Author = "François Chollet", ISBN = "9781617294433", LoanedTo = 2, Title = "Deep Learning with Python" },
                        new { Id = 3, Author = "Morgan Bruce, Paulo A. Pereira", ISBN = "9781617294457", Title = "Microservices in Action" },
                        new { Id = 4, Author = "Craig Walls", ISBN = "9781617294945", Title = "Spring in Action, Fifth Edition" },
                        new { Id = 5, Author = "Alessandro Negro", ISBN = "9781617295645", Title = "Graph-Powered Machine Learning" }
                    );
                });

            modelBuilder.Entity("Bookshelf.BL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Name = "Scott Guthrie" },
                        new { Id = 2, Name = "Robert C. Martin" },
                        new { Id = 3, Name = "Damian Edwards" }
                    );
                });

            modelBuilder.Entity("Bookshelf.BL.Book", b =>
                {
                    b.HasOne("Bookshelf.BL.User", "LoanedToUser")
                        .WithMany("LoanedBooks")
                        .HasForeignKey("LoanedTo");
                });
#pragma warning restore 612, 618
        }
    }
}
